[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Caleb Jasik <calebjasik@jasik.xyz>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"
